export { default as hero1 } from "./hero1.jpg"
export { default as hero2 } from "./hero2.jpg"
export { default as hero3 } from "./hero3.jpg"
export { default as inspo1 } from "./inspo1.jpeg"
export { default as inspo2 } from "./inspo2.jpeg"
export { default as inspo3 } from "./inspo3.jpeg"
export { default as inspo4 } from "./inspo4.jpeg"